/* Runs against the real isolated dashboard, not mocked browser responses. */
const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const readline = require('node:readline');
const {chromium} = require('playwright');
(async () => {
  const child = spawn(process.env.PYTHON || 'python3', ['tests/browser_fixture.py'], {stdio: ['pipe', 'pipe', 'inherit']});
  const lines = readline.createInterface({input: child.stdout})[Symbol.asyncIterator]();
  let browser;
  try {
    const {value, done} = await lines.next();
    assert(!done, 'fixture failed to start');
    const fixture = JSON.parse(value);
    browser = await chromium.launch(process.env.CHROMIUM_PATH ? {executablePath: process.env.CHROMIUM_PATH} : {});
    const page = await browser.newPage({viewport: {width: 1440, height: 1000}, reducedMotion: 'reduce'});
    const errors = [];
    page.on('pageerror', e => errors.push(String(e)));
    await page.goto(fixture.url);
    const message = page.locator(`[data-message="${fixture.id}"]`).first();
    await message.waitFor();
    await message.click();
    await page.waitForFunction(text => document.querySelector('.message-text')?.textContent === text, fixture.text);
    assert.equal(await page.locator('.message-text img').count(), 0, 'message content must be escaped');
    await page.locator('#message-reader summary').filter({hasText: 'Message data'}).click();
    assert.match(await page.locator('#message-reader [data-section=payload]').innerText(), /FBN1/);
    assert.equal(await page.locator('.related-message').count(), 1, 'actual reply must be inspectable');
    await page.locator('#message-search').fill('Unique final phenotype');
    await page.waitForFunction(() => document.querySelectorAll('.message-row').length === 1);
    await page.locator('#message-search').fill('');
    await page.waitForFunction(() => document.querySelectorAll('.message-row').length === 2);
    const prior = await page.locator('.message-text').innerText();
    child.stdin.write('update\n');
    await lines.next();
    await page.waitForFunction(() => document.querySelectorAll('.message-row').length === 3);
    assert.equal(await page.locator('.message-text').innerText(), prior, 'updates must not replace selected message');
    assert(await page.locator('[data-section=payload]').evaluate(el => el.open), 'updates must retain expanded data');
    await page.locator('#pause-live').click();
    assert.match(await page.locator('#connection').innerText(), /paused/);
    await page.locator('.related-message').click();
    await page.waitForFunction(id => document.querySelector('.message-row[aria-pressed=true]')?.dataset.message !== id, fixture.id);
    await page.locator(`[data-message="${fixture.id}"]`).first().click();
    await page.waitForFunction(text => document.querySelector('.message-text')?.textContent === text, fixture.text);
    await page.locator('#pause-live').click();
    const downloadPromise = page.waitForEvent('download');
    await page.locator('#download-message').click();
    assert.equal((await downloadPromise).suggestedFilename(), 'wasteland-message.json');
    await page.locator('.related-message').click();
    await page.waitForFunction(id => document.querySelector('.message-row[aria-pressed=true]')?.dataset.message !== id, fixture.id);
    await page.locator('[data-page=discover]').click();
    await page.locator('.town-entry').first().waitFor();
    await page.locator('#directory-search').fill('bravo');
    await page.locator('[data-contact="bravo/contact"]').first().click();
    await page.waitForSelector('#compose-view:not([hidden])');
    assert.equal(await page.locator('#town').inputValue(), 'bravo');
    await page.locator('#text').fill('Draft must survive live refresh.');
    // A new conversation can be sent to the fixture's local guide without outside mail.
    await page.locator('#town').selectOption('alpha');
    await page.locator('#agent').selectOption('guide');
    await page.locator('#send').click();
    await page.waitForSelector('.message');
    assert.match(await page.locator('#messages').innerText(), /Draft must survive live refresh/);
    assert.equal(await page.locator('#text').inputValue(), '');
    await page.locator('[data-page=messages]').click();
    await page.setViewportSize({width: 390, height: 844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'mobile must not overflow');
    await page.screenshot({path: '/tmp/workspace-browser-mobile.png', fullPage: true});
    await page.locator('#operations-link').click();
    await page.waitForURL('**/operations');
    assert.match(await page.title(), /Town operations/);
    assert.deepEqual(errors, []);
    console.log('PASS: full text, payloads, real linked replies, full-text search, live updates, pause, download, discovery, named composition, mobile and operations');
  } finally {
    if (browser) await browser.close();
    child.stdin.end('stop\n');
    const timer = setTimeout(() => child.kill('SIGKILL'), 10000);
    await new Promise(resolve => child.exitCode !== null ? resolve() : child.once('exit', resolve));
    clearTimeout(timer);
  }
})().catch(error => {console.error(error); process.exitCode = 1});
